services:
  postgres-surge:
    image: postgres:15-alpine
    container_name: postgres-surge
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: surge_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - surge-network

  redis-surge:
    image: redis:7-alpine
    container_name: redis-surge
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redisdata:/data
    networks:
      - surge-network

  rabbitmq-surge:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-surge
    ports:
      - "5672:5672" #AMQP protocol port
      - "15672:15672" #Managemein UI dashboard port
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitdata:/var/lib/rabbitmq
    networks:
      - surge-network


  datadog-agent:
    image: gcr.io/datadoghq/agent:latest
    container_name: datadog-agent
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=us5.datadoghq.com
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_HOSTNAME=surge-local
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT=0.0.0.0:4317
    ports:
      - "8126:8126"
      - "4317:4317"
    networks:
      - surge-network

volumes:
  pgdata:
  redisdata:
  rabbitdata:

networks:
  surge-network:
    driver: bridge