apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: surge-pubsub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: host
      value: "amqp://surge_guest:surge_secret@localhost:5672"