apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: surge-pubsub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: hostname
      value: "localhost"
    - name: port
      value: "5672"
    - name: username       # <-- This was the culprit!
      secretKeyRef:
        name: RABBITMQ_USER
        key: RABBITMQ_USER
    - name: password
      secretKeyRef:
        name: RABBITMQ_PASSWORD
        key: RABBITMQ_PASSWORD
auth:
  secretStore: surge-secretstore