server:
  port: 8083

spring:
  application:
    name: order-service

  threads:
    virtual:
      enabled: true

  # PostgreSQL Connection stays!
  datasource:
    url: jdbc:postgresql://localhost:5432/surge_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true